/// <reference types="vitest/config" />
import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig(({ mode }) => {
  // Vite only exposes VITE_* variables to the browser. The Supabase/Vercel
  // integration provides SUPABASE_URL and SUPABASE_ANON_KEY (and NEXT_PUBLIC_
  // copies) instead, so map exactly those two public values onto the names the
  // app reads. Nothing else is read here; the service-role key in particular
  // must never reach the bundle.
  const env = { ...loadEnv(mode, process.cwd(), ""), ...process.env };
  const url = env.VITE_SUPABASE_URL ?? env.SUPABASE_URL ?? env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const anonKey = env.VITE_SUPABASE_ANON_KEY ?? env.SUPABASE_ANON_KEY ?? env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
    env.SUPABASE_PUBLISHABLE_KEY ?? env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "";
  if (!url || !anonKey) {
    console.warn("vite: SUPABASE_URL / SUPABASE_ANON_KEY (or VITE_ equivalents) are not set; the app will fail at startup.");
  }
  return {
    plugins: [react()],
    define: {
      "import.meta.env.VITE_SUPABASE_URL": JSON.stringify(url),
      "import.meta.env.VITE_SUPABASE_ANON_KEY": JSON.stringify(anonKey),
    },
    test: {
      // Pure modules run in node. Anything that renders (*.test.tsx) runs in
      // jsdom; it can't be the default because Vite applies its browser file
      // guard there, which blocks states.test.ts from reading the migrations.
      projects: [
        { extends: true, test: { name: "node", include: ["src/**/*.test.ts"], environment: "node" } },
        {
          extends: true,
          test: { name: "dom", include: ["src/**/*.test.tsx"], environment: "jsdom", setupFiles: ["src/test/setup.ts"] },
        },
      ],
      coverage: {
        provider: "v8",
        include: ["src/**/*.{ts,tsx}"],
        exclude: [
          "src/**/*.test.{ts,tsx}",
          "src/test/**",
          // Generated by `supabase gen types`.
          "src/lib/database.types.ts",
          // Mounts <App /> into index.html; nothing to assert.
          "src/main.tsx",
        ],
        reporter: ["text-summary", "text", "lcov"],
        thresholds: { lines: 80, statements: 80, functions: 80, branches: 80 },
      },
    },
  };
});
